#!/usr/bin/env fish

if test (count $argv) -ne 1
    echo "Usage: fish ~/dotfiles/codex/assemble-agents.fish <profile>"
    echo "Example: fish ~/dotfiles/codex/assemble-agents.fish desktop"
    exit 2
end

set -l profile $argv[1]
set -l codex_repo (dirname (status --current-filename))
set -l shared_file "$codex_repo/AGENTS.md"
set -l machine_file "$codex_repo/machines/$profile.md"
set -l target_file ~/.codex/AGENTS.md
set -l marker '# Generated by Codex profile assembler; edit the source files in ~/dotfiles/codex/'

if not test -f $shared_file
    echo "Shared instructions not found: $shared_file" >&2
    exit 1
end

if not test -f $machine_file
    echo "Machine profile not found: $machine_file" >&2
    echo "Preserve the existing machine-specific AGENTS.md there first." >&2
    exit 1
end

mkdir -p ~/.codex

if test -e $target_file; or test -L $target_file
    set -l first_line (head -n 1 $target_file 2>/dev/null)
    if not string match -q '*Generated by Codex profile assembler*' -- $first_line
        set -l backup "$target_file.backup."(date +%Y%m%d-%H%M%S)
        mv $target_file $backup
        echo "Preserved the previous global instructions at $backup"
    end
end

begin
    echo $marker
    echo
    cat $shared_file
    echo
    echo "# Machine-specific instructions: $profile"
    echo
    cat $machine_file
end > $target_file

echo "Installed combined Codex instructions for profile '$profile' at $target_file"
